---

# Application settings.
virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"
virtualenv_python_version: "{{ base_python_package }}"

# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps
